---
- hosts: local
  become: yes
  vars:
    app_name: Franz
    app_url: https://github.com/meetfranz/franz/releases/download/v5.5.0/franz-5.5.0.dmg
    installer_type: app
    install_method: dmg
    download_file_type: dmg
  roles:
    - setup
    - installer
    - cleanup