---
- hosts: local
  become: yes
  vars:
    app_name: Keka
    app_url: https://d.keka.io/
    installer_type: app
    install_method: dmg
    download_file_type: dmg
  roles:
    - setup
    - installer
    - cleanup
