---
- name: Install Libre Office
  hosts: local
  become: yes
  vars:
    app_name: LibreOffice
    app_url: http://download.documentfoundation.org/libreoffice/stable/7.0.2/mac/x86_64/LibreOffice_7.0.2_MacOS_x86-64.dmg
    installer_type: app
    install_method: dmg
    download_file_type: dmg
  roles: 
    - setup
    - installer
    - cleanup
