---
- hosts: local
  become: yes
  vars:
    app_name: Element
    app_url: https://packages.riot.im/desktop/install/macos/Element.dmg
    installer_type: app
    install_method: dmg
    download_file_type: dmg
  roles:
    - setup
    - installer
    - cleanup