---
- hosts: local
  become: yes
  vars:
    app_name: SkypeForBussines
    app_url: https://www.microsoft.com/ru-RU/download/confirmation.aspx?id=54108
    installer_type: app
    install_method: dmg
    download_file_type: dmg
  roles:
    - setup
    - installer
    - cleanup