---
- hosts: local
  become: yes
  vars:
    app_name: Sublime Text
    app_url: https://download.sublimetext.com/Sublime%20Text%20Build%203211.dmg
    installer_type: app
    download_file_type: dmg
    install_method: dmg
  roles: 
    - setup
    - installer
    - cleanup
   
