---
- hosts: local
  become: yes
  vars:
    app_name: Telegram
    app_url: https://telegram.org/dl/macos
    installer_type: app
    install_method: dmg
    download_file_type: dmg
  roles:
    - setup
    - installer
    - cleanup