---
- hosts: local
  become: yes
  vars:
    app_name: ThunderBird
    app_url: https://download.mozilla.org/?product=thunderbird-78.1.1-SSL&os=osx&lang=ru
    installer_type: app
    install_method: dmg
    download_file_type: dmg
  roles:
    - setup
    - installer
    - cleanup