---
- hosts: local
  become: yes
  vars:
    app_name: TunnelBlick
    app_url: https://tunnelblick.net/release/Latest_Tunnelblick_Stable.dmg
    installer_type: app
    install_method: dmg
    download_file_type: dmg
  roles:
    - setup
    - installer
    - cleanup
